#!/bin/sh

##check mode,if AP/UR,exit	
local sys_mode=$(get_sys_mode)
[ "$sys_mode" == "2" -o "$sys_mode" == "3" ] && exit 0

defaultwan=$(uci get network.general.defaultWan)
ETH_WAN=$(uci_get network $defaultwan ifname)
PPPOE_WAN="pppoe"-"$defaultwan"

ETH_WANIP=$(ifconfig $ETH_WAN | grep "inet addr")
PPPOE_WANIP=$(ifconfig $PPPOE_WAN | grep "inet addr")

##need to check hardware NAT.

if [ "$ETH_WANIP" == "" ] && [ "$PPPOE_WANIP" == "" ]; then
	exit 0
fi

if [ -z "$DHCP_STATUS" -o "$DHCP_STATUS" != "renew" ];then
	/sbin/act_igmp
	echo "Init igmpproxy"
fi
