#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

. /etc/functions.sh

START=11

boot() {
	##Trigger at samba initial process.
	exit 0
}

start() {
	##check ucitrack type:system option:init ,led-->password
	
	sys_track=`/sbin/uci get ucitrack.@system[0].init`
	
	[ $sys_track=="led" ]&&{
		/sbin/uci set ucitrack.@system[0].init="password"
		/sbin/uci commit ucitrack
	}

	if [ -f /etc/passwd+ ]; then
		rm /etc/passwd+
	fi

	if [ -f /etc/shadow+ ]; then
		rm /etc/shadow+
	fi
	
	##For Console Debug
#	local ckDebugAccount=$(cat /etc/passwd|grep supervisor)
#	[ -z "$ckDebugAccount" ] && echo "supervisor::0:0:supervisor:/:/bin/ash" >> /etc/passwd
#	(echo supervisor; sleep 1; echo supervisor) | passwd supervisor

	##Max 5 account
	for i in 0 1 2 3 4
	do
		local username=$(uci get account.@account[$i].username)
		local password=$(uci get account.@account[$i].password)
		local privilege=$(uci get account.@account[$i].privilege)
		[ -z "$username" ] && continue
		
		##check account
		local curAccount=$(cat /etc/passwd |grep $username: |awk -F":" '{print $1}' )		
		if [ -z "$curAccount" -a "$curAccount" != "$username" ];then
			##Add username
			if [ "$privilege" == "1" ];then
				echo "$username::0:0:$username:/:/bin/ash" >> /etc/passwd
			else
				echo "$username::0:0:$username:/:/bin/fail" >> /etc/passwd
			fi		
		fi

		##Set password
		(echo $password; sleep 1; echo $password) | passwd $username

	done

	#protect login root id
#	chk_password=$(cat /etc/passwd |grep root:)
#        [ -z "$chk_password" ] && {
#                echo "root::0:0:root:/:/bin/ash" >> /etc/passwd
#        }

#	config_load system
#	config_get password main pwd
#	(echo $password; sleep 1; echo $password) | passwd 

	if [ -f /etc/passwd+ ]; then
		rm /etc/passwd+
	fi
}

stop() {
	
	##Max 5 account
	for i in 0 1 2 3 4
	do
		local username=$(uci get account.@account[$i].username)
		local password=$(uci get account.@account[$i].password)
		local oldName=$(uci get account.@account[$i].oldname)

		[ -z "$oldName" ] && continue
		
		deluser "$oldName"
	done

}
